const UPDATE_INTERRUPTOR = "UPDATE_INTERRUPTOR";
const UPDATE_VSTS = "UPDATE_VSTS";
const UPDATE_WORKITEM = "UPDATE_WORKITEM";

export default {
    types: {
        UPDATE_INTERRUPTOR,
        UPDATE_VSTS,
        UPDATE_WORKITEM
    }
}